<a href="https://colab.research.google.com/github/adiban17/PyTorch-Tutorial/blob/main/00_PyTorch_Fundamentalsipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Welcome to Pytorch Fundamentals !")

Welcome to Pytorch Fundamentals !


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.9.0+cpu


## Introduction to Tensors

### Creating tensors
Pytorch tensors are created using `torch.tensor()`

In [3]:
# scalars
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as Python int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# matrix
matrix = torch.tensor([[7,8],
                       [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
matrix.ndim

2

In [11]:
matrix.shape

torch.Size([2, 2])

In [12]:
matrix[1]

tensor([ 9, 10])

In [13]:
# tensor
TENSOR = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [17]:
TENSOR[0][1]

tensor([4, 5, 6])

### Random Tensor
Why random tensors ?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers to better represent the data.
`start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [18]:
# create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2217, 0.0192, 0.5606, 0.7866],
        [0.3228, 0.3740, 0.9892, 0.0719],
        [0.6850, 0.4586, 0.6600, 0.7496]])

In [19]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [20]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

In [23]:
# using torch.arange()
zero_to_ten = torch.arange(0,10)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
one_to_hundred = torch.arange(start=0, end=101, step=2)
one_to_hundred

tensor([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
         28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,  54,
         56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,
         84,  86,  88,  90,  92,  94,  96,  98, 100])

In [25]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes
**Note**:
Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & Deep Learning:
1. Tensors not right datatype
2. Tensor not right shape
3. Tensors not right device

In [26]:
# float32 tensors
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,  # what datatype is the tensor (eg: float32 or float16)
                               device=None, # which device is your tensor on ?
                               requires_grad=False  # whether or not to track gradients with the tensor
                               )
float_32_tensor

tensor([3., 6., 9.])

In [27]:
float_16_tensor = torch.tensor([1,2,3],
                               dtype=torch.float16)
float_16_tensor

tensor([1., 2., 3.], dtype=torch.float16)

In [28]:
(float_16_tensor * float_32_tensor).dtype

torch.float32

### Getting information from tensors

1. Tensors not right datatype - to get datatype , can use `tensor.dtype`
2. Tensor not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not right device - to get device from a tensor, can use `tensor.device`

In [29]:
# create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.7145, 0.1995, 0.3974, 0.2548],
        [0.3962, 0.8591, 0.0245, 0.7017],
        [0.9767, 0.9136, 0.5093, 0.3405]])

In [30]:
# Find out details about some_tensor
print(some_tensor)
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.shape}")
print(f"Device tensor is on:{some_tensor.device}")

tensor([[0.7145, 0.1995, 0.3974, 0.2548],
        [0.3962, 0.8591, 0.0245, 0.7017],
        [0.9767, 0.9136, 0.5093, 0.3405]])
Datatype of tensor:torch.float32
Shape of tensor:torch.Size([3, 4])
Device tensor is on:cpu


### Manipulating Tensors (Tensor Operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [31]:
# create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [32]:
# multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [33]:
# subtract 10
tensor - 10

tensor([-9, -8, -7])

In [34]:
# try out PyTorch in-built functions
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix Multiplication
Two main ways to perform multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rukes that performing mtrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
2. The resulting matrix will have the shape of the **outer dimensions**:
* `(3,2) @ (2,3) -> (2,2)`
* `(2,3) @ (3,2) -> (2,2)`

In [35]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals tensor([1, 4, 9])


In [36]:
# matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [37]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 841 µs, sys: 983 µs, total: 1.82 ms
Wall time: 2.19 ms


In [38]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 424 µs, sys: 0 ns, total: 424 µs
Wall time: 431 µs


tensor(14)

### One of the most common errors in deep learning : shape errors

In [39]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [4,5],
                         [23,54]])

In [40]:
torch.matmul(tensor_A.T, tensor_B)

tensor([[134, 295],
        [168, 364]])

In [41]:
tensor_A.T.shape, tensor_B.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

In [42]:
tensor_A * tensor_B

tensor([[  7,  20],
        [ 12,  20],
        [115, 324]])

In [43]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original Shape: tensor_A={tensor_A.shape}, tensor_B={tensor_B.shape}")
print(f"New shapes: tensor_A={tensor_A.shape} (same as above), tensor_B.T={tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"Output Shape:{output.shape}")

Original Shape: tensor_A=torch.Size([3, 2]), tensor_B=torch.Size([3, 2])
New shapes: tensor_A=torch.Size([3, 2]) (same as above), tensor_B.T=torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  14, 131],
        [ 61,  32, 285],
        [ 95,  50, 439]])
Output Shape:torch.Size([3, 3])


### Finding the min, max, mean, sum, etc (tensor aggregation)

In [44]:
# create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [45]:
# find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [46]:
# find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [47]:
# find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

### Finding the positional min and max

In [48]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [49]:
# find the position in tensor that has minimum value with argmin() -> returns index value
x.argmin()

tensor(0)

In [50]:
x[0]

tensor(0)

In [51]:
# find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [52]:
x[9]

tensor(90)

## Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimension to a target tensor
* Unsqueeze - add a `1` dimension to a taregt tensor
* Permute - Return a view of the input with dimensions permutes (swapped) in a certain way

In [53]:
# Let's create a tensor
import torch
x = torch.arange(1. , 13.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [54]:
# Add an extra dimension
x_reshaped = x.reshape(2,3,2)
x_reshaped, x_reshaped.shape

(tensor([[[ 1.,  2.],
          [ 3.,  4.],
          [ 5.,  6.]],
 
         [[ 7.,  8.],
          [ 9., 10.],
          [11., 12.]]]),
 torch.Size([2, 3, 2]))

In [55]:
# change the view
z = x.view(1,12)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([1, 12]))

In [56]:
# changing z changes x (beacuse a view of a tensor shares the same memory as the original)
z[:,0] = 5
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]))

In [57]:
# stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [72]:
# torch.squeeze() - removes all single dimensions from a target tensor
x = x.reshape(1,12)
print(f"Inital Shape of X : {x.shape}\nX:{x}\nNew Shape of X : {x.squeeze().shape}\nNew X : {x.squeeze()}")


Inital Shape of X : torch.Size([1, 12])
X:tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])
New Shape of X : torch.Size([12])
New X : tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])


In [79]:
# torch.unaqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target:{x}\nPrevious shape: {x.shape}")
print(f"New tensor: {x.unsqueeze(dim=0)}\nNew shape:{x.unsqueeze(dim=0).shape}")

Previous target:tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])
Previous shape: torch.Size([1, 12])
New tensor: tensor([[[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]])
New shape:torch.Size([1, 1, 12])


In [83]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) #[height, width, color_channels]

# permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1)  # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") #[color_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [87]:
x_original[0,0,0] = 1234
x_original[0,0,0]

tensor(1234.)

## Indexing (selecting data from tensors)
Indexing with PyTorch is similar to indexing with NumPy.

In [90]:
# create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [91]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [92]:
# Let's index on our middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [94]:
# Let's index on the most inner bracket (last dimension)
x[0][2][2]

tensor(9)

In [95]:
# you can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [96]:
# get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [97]:
# get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [99]:
# get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [101]:
# index on x to return 9
x[0][2][2]

tensor(9)

In [103]:
# index on x to return 3,6,9
x[:,:,2]

tensor([[3, 6, 9]])

## PyTorch tensors and NumPy
NumPy is a opoular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.
* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [108]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)  # warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [109]:
# change the value of array, what will this do to `tensor` ?
array = array + 1

In [110]:
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [111]:
# tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [112]:
# change the tensor, what will happen to `numpy_tensor` ?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)
In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again ...`

To reduce randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [114]:
import torch

# create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.4612, 0.7376, 0.3863, 0.5446],
        [0.4200, 0.7685, 0.7963, 0.4525],
        [0.1278, 0.6036, 0.8218, 0.6265]])
tensor([[0.2759, 0.5118, 0.5182, 0.9456],
        [0.0869, 0.4950, 0.4822, 0.5672],
        [0.8653, 0.5383, 0.9234, 0.6186]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [122]:
# let's make some random but reproducible tensors
import torch

# set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


## Running tensor and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thnals to CUDA + NVIDIA hardware + PyTorch wokring behind the scenes to make everything good

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's a lot of options ....
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2,3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation

In [2]:
!nvidia-smi

Fri Jan 16 19:03:37 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   54C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### 2. Check for GPU acess with PyTorch

In [3]:
# check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code

eg: run on GPU if available, else defaut to CPU

In [4]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [5]:
# count the number of devices
torch.cuda.device_count()

1

### 3. Putting tensors and models on the GPU
The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [7]:
# creating a tensor (default on the CPU)
tensor = torch.tensor([1,2,3])

# tensor not on GPU
print(tensor, tensor.device)


tensor([1, 2, 3]) cpu


In [8]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [9]:
# if tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [13]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu.device

'cpu'