<a href="https://colab.research.google.com/github/adiban17/PyTorch-Tutorial/blob/main/00_PyTorch_Fundamentalsipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Welcome to Pytorch Fundamentals !")

Welcome to Pytorch Fundamentals !


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.9.0+cpu


## Introduction to Tensors

### Creating tensors
Pytorch tensors are created using `torch.tensor()`

In [ ]:
# scalars
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# matrix
matrix = torch.tensor([[7,8],
                       [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
matrix[1]

tensor([ 9, 10])

In [ ]:
# tensor
TENSOR = torch.tensor([[[1,2,3],
                       [4,5,6],
                       [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
TENSOR[0][1]

tensor([4, 5, 6])

### Random Tensor
Why random tensors ?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers to better represent the data.
`start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [ ]:
# create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1372, 0.3159, 0.3753, 0.8184],
        [0.0591, 0.4402, 0.5815, 0.8437],
        [0.3763, 0.8174, 0.2787, 0.7895]])

In [34]:
# create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, color channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [37]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [38]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [39]:
ones.dtype

torch.float32

In [41]:
# using torch.arange()
zero_to_ten = torch.arange(0,10)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
one_to_hundred = torch.arange(start=0, end=101, step=2)
one_to_hundred

tensor([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
         28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,  54,
         56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,
         84,  86,  88,  90,  92,  94,  96,  98, 100])

In [43]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes
**Note**:
Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & Deep Learning:
1. Tensors not right datatype
2. Tensor not right shape
3. Tensors not right device

In [47]:
# float32 tensors
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,  # what datatype is the tensor (eg: float32 or float16)
                               device=None, # which device is your tensor on ?
                               requires_grad=False  # whether or not to track gradients with the tensor
                               )
float_32_tensor

tensor([3., 6., 9.])

In [50]:
float_16_tensor = torch.tensor([1,2,3],
                               dtype=torch.float16)
float_16_tensor

tensor([1., 2., 3.], dtype=torch.float16)

In [52]:
(float_16_tensor * float_32_tensor).dtype

torch.float32

### Getting information from tensors

1. Tensors not right datatype - to get datatype , can use `tensor.dtype`
2. Tensor not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not right device - to get device from a tensor, can use `tensor.device`

In [53]:
# create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4004, 0.3763, 0.2221, 0.1289],
        [0.5828, 0.0929, 0.2222, 0.7385],
        [0.8664, 0.5943, 0.7561, 0.7163]])

In [54]:
# Find out details about some_tensor
print(some_tensor)
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.shape}")
print(f"Device tensor is on:{some_tensor.device}")

tensor([[0.4004, 0.3763, 0.2221, 0.1289],
        [0.5828, 0.0929, 0.2222, 0.7385],
        [0.8664, 0.5943, 0.7561, 0.7163]])
Datatype of tensor:torch.float32
Shape of tensor:torch.Size([3, 4])
Device tensor is on:cpu


### Manipulating Tensors (Tensor Operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [56]:
# create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [57]:
# multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [58]:
# subtract 10
tensor - 10

tensor([-9, -8, -7])

In [60]:
# try out PyTorch in-built functions
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix Multiplication
Two main ways to perform multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rukes that performing mtrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
2. The resulting matrix will have the shape of the **outer dimensions**:
* `(3,2) @ (2,3) -> (2,2)`
* `(2,3) @ (3,2) -> (2,2)`

In [64]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals tensor([1, 4, 9])


In [68]:
# matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [69]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 2.01 ms, sys: 0 ns, total: 2.01 ms
Wall time: 3.04 ms


In [70]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 634 µs, sys: 23 µs, total: 657 µs
Wall time: 554 µs


tensor(14)

### One of the most common errors in deep learning : shape errors

In [74]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

tensor_B = torch.tensor([[7,10],
                         [4,5],
                         [23,54]])

In [78]:
torch.matmul(tensor_A.T, tensor_B)

tensor([[134, 295],
        [168, 364]])

In [77]:
tensor_A.T.shape, tensor_B.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

In [79]:
tensor_A * tensor_B

tensor([[  7,  20],
        [ 12,  20],
        [115, 324]])

In [82]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original Shape: tensor_A={tensor_A.shape}, tensor_B={tensor_B.shape}")
print(f"New shapes: tensor_A={tensor_A.shape} (same as above), tensor_B.T={tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"Output Shape:{output.shape}")

Original Shape: tensor_A=torch.Size([3, 2]), tensor_B=torch.Size([3, 2])
New shapes: tensor_A=torch.Size([3, 2]) (same as above), tensor_B.T=torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  14, 131],
        [ 61,  32, 285],
        [ 95,  50, 439]])
Output Shape:torch.Size([3, 3])


### Finding the min, max, mean, sum, etc (tensor aggregation)

In [83]:
# create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [84]:
# find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [85]:
# find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [88]:
# find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

### Finding the positional min and max

In [89]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [91]:
# find the position in tensor that has minimum value with argmin() -> returns index value
x.argmin()

tensor(0)

In [94]:
x[0]

tensor(0)

In [95]:
# find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [97]:
x[9]

tensor(90)

## Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimension to a target tensor
* Unsqueeze - add a `1` dimension to a taregt tensor
* Permute - Return a view of the input with dimensions permutes (swapped) in a certain way

In [105]:
# Let's create a tensor
import torch
x = torch.arange(1. , 13.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [110]:
# Add an extra dimension
x_reshaped = x.reshape(2,3,2)
x_reshaped, x_reshaped.shape

(tensor([[[ 1.,  2.],
          [ 3.,  4.],
          [ 5.,  6.]],
 
         [[ 7.,  8.],
          [ 9., 10.],
          [11., 12.]]]),
 torch.Size([2, 3, 2]))

In [112]:
# change the view
z = x.view(1,12)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([1, 12]))

In [113]:
# changing z changes x (beacuse a view of a tensor shares the same memory as the original)
z[:,0] = 5
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]))

In [116]:
# stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])